import chatgptIcon from '../../assets/chatgptIcon.png';
import bingcoloricon from '../../assets/bingcoloricon.png';
const MoreUsData = [
    {
        id: 1,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: chatgptIcon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 200,
        views: 12,
        viewsCount: "K",
        bookmarksCount: "K",
        badge: "Free",
    },
    {
        id: 2,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: bingcoloricon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 176,
        views: 17,
        viewsCount: "M",
        bookmarksCount: "K",
        badge: "Free",
    },
    {
        id: 3,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: chatgptIcon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 78,
        views: 87,
        viewsCount: "M",
        bookmarksCount: "M",
        badge: "Paid",
    },
    {
        id: 4,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: chatgptIcon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 88,
        views: 67,
        viewsCount: "k",
        bookmarksCount: "K",
        badge: "Free",
    },
    {
        id: 5,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: chatgptIcon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 986,
        views: 32,
        viewsCount: "M",
        bookmarksCount: "K",
        badge: "Free",

    },
    {
        id: 6,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: chatgptIcon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 986,
        views: 32,
        viewsCount: "K",
        bookmarksCount: "M",
        badge: "Paid",
    },
    {
        id: 7,
        title : "ChatGPT",
        organization : "OpenAi",
        logo: chatgptIcon,
        description: "These tools will help designers to experiment with different prompts and also receive feedback on the designs you created",
        bookmarks: 3443,
        views: 45,
        viewsCount: "K",
        bookmarksCount: "M",
        badge: "Paid",
    }
]
export default MoreUsData;